Fix non 3d annotations appearing in 3D viewport
RadicalImaging/MCornerstone3D pull request #9
Opened 2023-12-15 19:11 UTC by rodrigobasilio2022

### Context

### Changes & Results

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2023-12-18 14:38 UTC, ladeirarodolfo requested changes
Few comments only. Thanks Rodrigo

2023-12-18 14:38 UTC, ladeirarodolfo commented on packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
> +      if (annotation.metadata.toolName !== 'Length3D') {
The solution has to be generic.

For that create a property on tools and check it here. Something like
return metadata.toolContext !== '3D'

2023-12-18 14:38 UTC, ladeirarodolfo commented on packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
> +      if (!annotation.isVisible) {
I believe the check for visible or not tools are done already in other place, no?

2023-12-18 15:35 UTC, rodrigobasilio2022 commented on packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
> +      if (annotation.metadata.toolName !== 'Length3D') {
done

2023-12-18 15:36 UTC, rodrigobasilio2022 commented on packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
> +      if (!annotation.isVisible) {
Here we filter to not habve to handle it in renderAnnotation. I dont see a problem. We could maintain both for code safety

2023-12-18 17:07 UTC, ladeirarodolfo requested changes

2023-12-18 17:07 UTC, ladeirarodolfo commented on packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
> +      if (!annotation.isVisible) {
I would agree with you, but less change in this layer better will be

2023-12-18 17:07 UTC, ladeirarodolfo commented on packages/tools/src/types/AnnotationTypes.ts
> +     * The context of the annotation: 2D or 3D
Add a comment saying if empty it will be treated as 2d

2023-12-18 17:08 UTC, ladeirarodolfo requested changes

2023-12-18 17:08 UTC, ladeirarodolfo commented on packages/tools/src/utilities/planar/filterAnnotationsForDisplay.ts
> +      if (annotation.metadata?.toolContext !== '3D') {
return (annotation.metadata?.toolContext?.toUpperCase()) === '3D', no?

(less code)

2023-12-21 17:22 UTC, ladeirarodolfo approved these changes

2023-12-21 17:22 UTC, merged